# Site settings
title: Benjamin Blackman: Full Stack Web Developer
header-img: img/home-bg.png
email: bblkmn5@gmail.com
copyright_name: bblkmn5
description: > # this means to ignore newlines until "baseurl:"
  A collection of my time working through Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bblkmn5
learn_profile: bblkmn5
email_username: bblkmn5@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
